name: go-package

on:
  push:
    tags: ['*']

permissions:
  contents: write

jobs:
  dfljksdjlkfdslk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Test Action
        uses: evg4b/goreleaser-npm-publisher-action@debug
        with:
          milliseconds: 1000

      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - name: goreleaser-npm-publisher publish
        run: npx -y goreleaser-npm-publisher@latest publish --clear --project . --builder "go-package" --prefix "@wserdtryftvubhijnokmpl" --description "A simple dev HTTP/HTTPS reverse proxy for replacing CORS headers."
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
